---
site_name: Pydo
site_author: Lyz
site_url: https://lyz-code.github.io/pydo
nav:
  - Overview: index.md
  - Basic Usage: basic_usage.md
  - Advanced Usage:
      - Areas: areas.md
      - Tags: tags.md
      - Dates: dates.md
      - Recurrence: recurrence.md
      - Priority: priority.md
      - Estimate: estimate.md
      - Value: objective_value.md
      - Willpower: willpower.md
      - Fun: fun.md
      - Export: export.md
  - Customization:
      - Sorting: sorting.md
      - Reports: reports.md
      - Colors: colors.md
  - Contributing: contributing.md
  - Developing:
      - Contributing: contributing.md
      - Architecture Decision Records:
          - adr/adr.md
          - '001: Deprecation of Fulids': adr/001-change-id-from-str-to-int
          - '00X: Subtasks and steps': adr/0xx-subtasks-and-steps
          - '00X: Agenda': adr/0xx-agenda
  - Reference: reference.md
  - Related: related.md

plugins:
  - search
    #  - mkdocstrings:
    #      handlers:
    #        python:
    #          rendering:
    #            show_root_heading: true
    #            heading_level: 1
    #      watch:
    #        - src
  - autolinks
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - mermaid2:
      arguments:
        securityLevel: loose

markdown_extensions:
  - abbr
  - def_list
  - admonition
  - markdown_include.include:
      base_path: docs
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  custom_dir: docs/theme
  logo: images/logo.bmp
  features:
    - navigation.instant
  palette:
    primary: blue grey
    accent: light blue

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css

repo_name: lyz-code/pydo
repo_url: https://github.com/lyz-code/pydo
