site_name: Pydo documentation
site_author: Lyz
site_url: https://lyz-code.github.io/pydo
nav:
  - Introduction: 'index.md'
  - Basic Usage: 'basic_usage.md'
  - Configuration: 'configuration.md'
  - Update: 'update.md'
  - Advanced Usage:
    - Projects: 'advanced_usage/projects.md'
    - Tags: 'advanced_usage/tags.md'
    - Dates: 'advanced_usage/dates.md'
    - Priority: 'advanced_usage/priority.md'
    - Recurrence: 'advanced_usage/recurrence.md'
    - Estimate: 'advanced_usage/estimate.md'
    - Value: 'advanced_usage/objective_value.md'
    - Willpower: 'advanced_usage/willpower.md'
    - Fun: 'advanced_usage/fun.md'
    - Export: 'advanced_usage/export.md'
  - Future Features: future_features.md
  - Contributing: 'contributing.md'
  - Developing:
    - Database Schema: 'developing/database_schema.md'
    - Friendly IDs: 'developing/fulids.md'
  - Related: 'related.md'

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  custom_dir: 'theme'
  logo: 'images/logo.bmp'
  palette:
    primary: 'blue grey'
    accent: 'light blue'

extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/links.css'

repo_name: 'lyz-code/pydo'
repo_url: 'https://github.com/lyz-code/pydo'
