[mypy]
ignore_missing_imports = False

[mypy-alembic.*]
ignore_missing_imports = True

[mypy-deepdiff.*]
ignore_missing_imports = True

[mypy-setuptools.*]
ignore_missing_imports = True

[mypy-click_default_group.*]
ignore_missing_imports = True

[mypy-factory.*]
ignore_missing_imports = True

[mypy-faker.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-ruamel.*]
ignore_missing_imports = True

[mypy-ulid.*]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-dateutil.parser.parserinfo.*]
ignore_missing_imports = True
