"""Add project

Revision ID: 747c1748c143
Revises: 3e31fd4ab929
Create Date: 2019-12-13 03:19:31.996219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747c1748c143'
down_revision = '3e31fd4ab929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('project', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'project')
    # ### end Alembic commands ###
