"""Added Recurrent task

Revision ID: aa061c0564ca
Revises: ade851e4a70f
Create Date: 2020-04-30 12:52:18.030386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa061c0564ca'
down_revision = 'ade851e4a70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrent_task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recurrence_type', sa.String(), nullable=True),
    sa.Column('recurrence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurrent_task')
    # ### end Alembic commands ###
