"""Initial schema

Revision ID: dec5ff8bd379
Revises: 
Create Date: 2019-12-14 12:38:26.743894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec5ff8bd379'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('default', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('choices', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('closed_utc', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('config')
    # ### end Alembic commands ###
